Update adb script from git version (has wait_reboot)

diff --git a/upgrade_testing/data/adb b/upgrade_testing/data/adb
--- a/upgrade_testing/data/adb
+++ b/upgrade_testing/data/adb
@@ -263,12 +263,13 @@ revert() {
     ubuntu_prepare_for_testing
 }
 
-reboot() {
+wait_reboot() {
     if [ -z "$FWD_PORT" ]; then
         echo "ERROR: Must pass --fwd-port" >&2
         exit 1
     fi
-    adb $ADBOPTS reboot
+    # wait until this fails because adbd shuts down
+    adb $ADBOPTS shell sleep 300 2>/dev/null || true
     wait_booted
     adb $ADBOPTS shell 'gdbus call -y -d com.canonical.PropertyService -o /com/canonical/PropertyService -m com.canonical.PropertyService.SetProperty ssh true >/dev/null'
     adb $ADBOPTS forward tcp:$FWD_PORT tcp:22
@@ -322,7 +323,7 @@ while true; do
             KEEP_POWERD_CLI="$1"
             shift;;
         --identity)
-            KNOWNHOSTS_LOCATION="$2"
+            IDENTITY_LOCATION="$2"
             shift 2;;
         --)
             shift;
@@ -346,8 +347,8 @@ case $cmd in
         open;;
     revert)
         revert;;
-    reboot)
-        reboot;;
+    wait-reboot)
+        wait_reboot;;
     cleanup)
         cleanup;;
     *)
